[package]
name = "libcrux-p384"
version = "0.0.1"
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rand = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
libcrux-kats = { workspace = true, features = ["ecdh"] }

[features]
# Provides private key generation API
rand = ["dep:rand"]

[package.metadata.docs.rs]
all-features = true
